<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEXdyvmx\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEXdyvmx/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerEXdyvmx.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerEXdyvmx\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerEXdyvmx\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'EXdyvmx',
    'container.build_id' => 'f9f0422e',
    'container.build_time' => 1775448615,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEXdyvmx');
